# Theta Subchain configuration
genesis:
  hash: "0x3c7673f2f46bf8fbdfdc8981aac5019986425a9c5bf282c2d736eb421f220e96"
p2p:
  port: 12100
rpc:
  enabled: true
log:
  levels: "*:info"
  #levels: "*:debug"
consensus:
  minBlockInterval: 1
subchain:
  mainchainEthRpcURL: "https://eth-rpc-api-testnet.thetatoken.org/rpc"
  subchainEthRpcURL: "http://localhost:19888/rpc"
  chainRegistrarOnMainchain: "0x359878c13F8690710FDCb2cDB6Da1c0A92661b9E"
  mainchainTFuelTB: "0x1678BbaB6Db608B27Dac2802C1d89E280b8C2C8f"
  mainchainTNT20TB: "0x02Cbc51C5bbc37F93ad211a5F405aab00B0951b1"
  mainchainTNT721TB: "0x0603E7fad093A88C9ADBC685808961FADDAfFF97"
  mainchainTNT1155TB: "0xD840b9662bf74Ae9838ccEf645E0D6d1573AA9E7"
  updateInterval: 3000
  # use the numerical EVM chainID for <YOUR_EVM_chainID> below, e.g. 360998877 
  chainID: 345612

